### ISSUE TITLE
Rss 中 item 的链接是否可以考虑替换成仓库链接？

### ISSUE THREAD

**Issue by jiannei** [guanguans/favorite-link#22]
现在 item 的链接是 git commit 提交地址，如果替换成 https://github.com/mr-punyapal/laravel-extended-relationships ，通过 RSS 订阅时可以更快地访问相应仓库。

![](https://raw.githubusercontent.com/jiannei/snc-pro/master/images/202312131313962.png)

效果类似于 https://sinan.fun/rss   ，解析 RSS 源 item 中的 title、link，访问 link 直达原始内容

![](https://raw.githubusercontent.com/jiannei/snc-pro/master/images/202312131320242.png)

**Comment by guanguans** [comment]
@jiannei 刚看到我看看后面重新搞一下，一直没时间弄这个。

**Comment by guanguans** [comment]
@jiannei 新订阅地址

[https://raw.githubusercontent.com/guanguans/favorite-link/master/README.rss](https://raw.githubusercontent.com/guanguans/favorite-link/master/README.rss)

**Comment by jiannei** [comment]
> `master`/README.rss (raw)

收到 https://sinan.fun/rss 中了 👍

**Comment by guanguans** [comment]
> > `master`/README.rss (raw)
> 
> 收录到 [sinan.fun/rss](https://sinan.fun/rss) 中了 👍

优秀 👍
